USE BAZINGA;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
U_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(30),
Email VARCHAR(128) UNIQUE,
DOB DATE,
Occupation VARCHAR(30),
Location VARCHAR(30),
Pass VARCHAR(128)
);

DROP TABLE IF EXISTS Contacts;
CREATE TABLE Contacts (
Con_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID1 MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
U_ID2 MEDIUMINT UNSIGNED REFERENCES Users(U_ID)
);

DROP TABLE IF EXISTS Groups;
CREATE TABLE Groups (
G_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
Name VARCHAR(30)
);


DROP TABLE IF EXISTS Posts;
CREATE TABLE Posts (
P_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
G_ID MEDIUMINT UNSIGNED REFERENCES Groups(G_ID),
Text VARCHAR(500),
Image VARCHAR(60)
);

DROP TABLE IF EXISTS Likes;
CREATE TABLE Likes (
L_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
P_ID MEDIUMINT UNSIGNED REFERENCES Posts(P_ID)
);

DROP TABLE IF EXISTS Comments;
CREATE TABLE Comments (
C_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
P_ID MEDIUMINT UNSIGNED REFERENCES Posts(P_ID),
Coment VARCHAR(100)
);

DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages (
M_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID1 MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
U_ID2 MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
Message VARCHAR(200)
);


DROP TABLE IF EXISTS Discussion;
CREATE TABLE Discussion (
D_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
Topic VARCHAR(30),
Discription VARCHAR(200)
);

DROP TABLE IF EXISTS DiscussionComments;
CREATE TABLE DiscussionComments (
DC_ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
U_ID MEDIUMINT UNSIGNED REFERENCES Users(U_ID),
Discussion VARCHAR(200)
);

