USE CODERS;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
Lib_ID MEDIUMINT UNSIGNED PRIMARY KEY,
User_Name VARCHAR(60),
Hash_Password VARCHAR(128),
Contact_Number BIGINT UNSIGNED UNIQUE, 
Univ_Roll_No INTEGER UNSIGNED UNIQUE,
Email_Id VARCHAR(128) UNIQUE,
Hostel VARCHAR(10),
Room_No VARCHAR(5),
Postal_Address VARCHAR(400),
Score TINYINT
);

DROP TABLE IF EXISTS Admins;
CREATE TABLE Admins (
Lib_ID MEDIUMINT UNSIGNED UNIQUE REFERENCES Users(Lib_ID)
);

INSERT INTO Users VALUES(1000,"Coders","c9b0ac5f31e80d0bfdcdd4cc7282e3d0","","","","","","",0);
INSERT INTO Admins VALUES(1000);

DROP TABLE IF EXISTS Challenges;
CREATE TABLE Challenges (
Challenge_ID TINYINT UNSIGNED PRIMARY KEY,
Challenge_Name VARCHAR(15),
Difficulty TINYINT UNSIGNED
);

DROP TABLE IF EXISTS Solutions;
CREATE TABLE Solutions(
Challenge_ID TINYINT UNSIGNED  REFERENCES Challenges(Challenge_ID),
Lib_ID MEDIUMINT UNSIGNED  REFERENCES Users(Lib_ID),
File_Name VARCHAR(30)
);

DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages (
Name VARCHAR(60),
Email_Id VARCHAR(128),
Message VARCHAR(400),
M_Id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE IF EXISTS Topics;
CREATE TABLE Topics (
Topic VARCHAR(30),
Lib_ID MEDIUMINT UNSIGNED  REFERENCES Users(Lib_ID),
Description VARCHAR(200),
T_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE IF EXISTS Comments;
CREATE TABLE Comments (
T_ID INTEGER NOT NULL REFERENCES Topics(T_ID),
Lib_ID MEDIUMINT UNSIGNED  REFERENCES Users(Lib_ID),
Commnt VARCHAR(200),
C_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY
);
